//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHogarDulceCorazonJoelGramajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adopciones()
        {
            this.Regreso_de_niños = new HashSet<Regreso_de_niños>();
            this.Asignar_padre_a_adopción = new HashSet<Asignar_padre_a_adopción>();
        }
    
        public int Adopción_de_niño { get; set; }
        public Nullable<int> Niño { get; set; }
        public System.DateTime Fecha_adopción { get; set; }
        public System.DateTime Fecha_mudanza { get; set; }
    
        public virtual Niños Niños { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regreso_de_niños> Regreso_de_niños { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asignar_padre_a_adopción> Asignar_padre_a_adopción { get; set; }
    }
}
