//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHogarDulceCorazonJoelGramajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignar_padre_a_adopción
    {
        public int Padre_adopción { get; set; }
        public Nullable<int> Adopción_de_niño { get; set; }
        public Nullable<int> Candidato_a_padre_adoptivo { get; set; }
    
        public virtual Adopciones Adopciones { get; set; }
        public virtual Candidatos_a_padres_adoptivos Candidatos_a_padres_adoptivos { get; set; }
    }
}
