//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHogarDulceCorazonJoelGramajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignar_padecimiento_a_ficha_médica
    {
        public int Código_de_asignación_padecimiento { get; set; }
        public System.DateTime Fecha_de_diagnóstico { get; set; }
        public Nullable<int> Padecimiento { get; set; }
        public string Código_ficha_médica { get; set; }
        public Nullable<int> Estado_de_tratamiento { get; set; }
    
        public virtual Fichas_médicas Fichas_médicas { get; set; }
        public virtual Padecimientos Padecimientos { get; set; }
        public virtual Estados_de_tratamientos Estados_de_tratamientos { get; set; }
    }
}
