//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHogarDulceCorazonJoelGramajo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseHogarEntities : DbContext
    {
        public DatabaseHogarEntities()
            : base("name=DatabaseHogarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adopciones> Adopciones { get; set; }
        public virtual DbSet<Asignar_padecimiento_a_ficha_médica> Asignar_padecimiento_a_ficha_médica { get; set; }
        public virtual DbSet<Asignar_padre_a_adopción> Asignar_padre_a_adopción { get; set; }
        public virtual DbSet<Candidatos_a_padres_adoptivos> Candidatos_a_padres_adoptivos { get; set; }
        public virtual DbSet<Estados_de_tratamientos> Estados_de_tratamientos { get; set; }
        public virtual DbSet<Fichas_médicas> Fichas_médicas { get; set; }
        public virtual DbSet<Géneros> Géneros { get; set; }
        public virtual DbSet<Niños> Niños { get; set; }
        public virtual DbSet<Padecimientos> Padecimientos { get; set; }
        public virtual DbSet<Regreso_de_niños> Regreso_de_niños { get; set; }
    }
}
