//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHogarDulceCorazonJoelGramajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Niños
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Niños()
        {
            this.Adopciones = new HashSet<Adopciones>();
            this.Fichas_médicas = new HashSet<Fichas_médicas>();
        }
    
        public int Niño { get; set; }
        public string Nombre { get; set; }
        public long CUI_niño { get; set; }
        public System.DateTime Fecha_nacimiento { get; set; }
        public Nullable<int> Género { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adopciones> Adopciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fichas_médicas> Fichas_médicas { get; set; }
        public virtual Géneros Géneros { get; set; }
    }
}
