//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoHogarDulceCorazonJoelGramajo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regreso_de_niños
    {
        public int Regreso_de_niño { get; set; }
        public Nullable<int> Adopción_de_niño { get; set; }
        public System.DateTime Fecha_regreso { get; set; }
        public string Motivo_regreso { get; set; }
    
        public virtual Adopciones Adopciones { get; set; }
    }
}
